name: BarDown
options:
  bundleIdPrefix: com.bardown
  deploymentTarget:
    iOS: "26.0"
  xcodeVersion: "26.2"
  defaultConfig: Debug
settings:
  SWIFT_VERSION: "6"
  TARGETED_DEVICE_FAMILY: "1,2"
packages:
  GlassKit:
    path: Packages/GlassKit
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher.git
    minorVersion: "8.0.0"
targets:
  BarDown:
    type: application
    platform: iOS
    sources:
      - path: BarDown
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.bardown.app
        INFOPLIST_GENERATION_MODE: GeneratedFile
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: "YES"
        SWIFT_EMIT_LOC_STRINGS: "YES"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        DEVELOPMENT_ASSET_PATHS: "\"BarDown/Preview Content\""
        INFOPLIST_KEY_APIBaseURL: "$(API_BASE_URL)"
        INFOPLIST_KEY_APIKey: "$(API_KEY)"
      configs:
        Debug:
          API_BASE_URL: "http://localhost:8080"
          API_KEY: ""
    dependencies:
      - package: GlassKit
      - package: Kingfisher
  BarDownTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: BarDownTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.bardown.app.tests
        GENERATE_INFOPLIST_FILE: "YES"
    dependencies:
      - target: BarDown
schemes:
  BarDown:
    build:
      targets:
        BarDown: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - BarDownTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
