name: BarDown
options:
  bundleIdPrefix: com.bardown
  deploymentTarget:
    iOS: "26.0"
  xcodeVersion: "26.2"
  defaultConfig: Debug
settings:
  SWIFT_VERSION: "6"
  TARGETED_DEVICE_FAMILY: "1,2"
packages:
  GlassKit:
    path: Packages/GlassKit
targets:
  BarDown:
    type: application
    platform: iOS
    sources:
      - path: BarDown
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.bardown.app
        INFOPLIST_GENERATION_MODE: GeneratedFile
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: "YES"
        SWIFT_EMIT_LOC_STRINGS: "YES"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        DEVELOPMENT_ASSET_PATHS: "\"BarDown/Preview Content\""
    dependencies:
      - package: GlassKit
schemes:
  BarDown:
    build:
      targets:
        BarDown: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
